per_listener_settings true

listener 1883
allow_anonymous true
max_qos 1
persistence true
persistence_location /mosquitto/data/
autosave_interval 1800
autosave_on_changes false

log_dest stdout
log_type all
log_timestamp_format %Y-%m-%dT%H:%M:%S

max_connections -1
max_queued_messages 2000

connection_messages true
